name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm test
